on:
  push:
    branches:
      - 'main'
env: 
  GKE_CLUSTER: micasino-staging-gke    # TODO: update to cluster name
  GKE_ZONE: southamerica-west1-c	   # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-hello-app # TODO: update deployment name if changed in deployment.yaml
  
jobs:
  # docker:    
  #   runs-on: ubuntu-latest
  #   environment: DEV
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     -
  #       name: Login to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/redistnetcore:${{ github.sha }}
  build-and-push-to-gcr-gke-service-account:
    name: Build & push - with service account
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v3      
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.B64_GCLOUD_SERVICE_ACCOUNT_JSON }}'
      - name: Building and pushing the image gcr   
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta # <- use this on your workflow
        with:
          # gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }} # <- not needed when used with google-github-actions/auth@v0
          registry: gcr.io
          project_id: ${{ secrets.GKE_PROJECT }}
          image_name: ${{ env.DEPLOYMENT_NAME }}
          image_tag: ${{ env.DEPLOYMENT_NAME }}-${{ github.sha }}, ${{ github.sha }}
          dockerfile: ./Dockerfile
          context: .
          target: build
      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Get the GKE credentials so we can deploy to the cluster
      - name: Get Credencials GKE
        run: |-         
          gcloud components install gke-gcloud-auth-plugin     
          gcloud components list          
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud container clusters get-credentials "${{ secrets.GKE_CLUSTER }}" --zone "$GKE_ZONE"
      
      - name: update kubernetes yaml
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            Deploy-k8s/02-redistnetcore.yml
          replacement-method: defined
        env:
          PROJECT_ID: ${{ secrets.GKE_PROJECT }}
          IMAGE_TAG: ${{ github.sha }}
          APP_NAME: ${{ env.DEPLOYMENT_NAME }}
          COMMIT: ${{ github.sha }}

      # # Deploy sample image to the GKE cluster
      # - name: Deploy
      #   run: |-
      #     kubectl apply -f ./Deploy-k8s/02-redistnetcore.yml
      #     kubectl rollout status deployment/$DEPLOYMENT_NAME
      #     kubectl get services -o wide